# Generated by Django 4.2.1 on 2023-05-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=255)),
                ('streetName', models.CharField(max_length=255)),
                ('houseNumber', models.IntegerField()),
                ('city', models.CharField(max_length=255)),
                ('postalCode', models.IntegerField()),
            ],
        ),
    ]
