# Generated by Django 4.2.1 on 2023-05-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholderName', models.CharField(max_length=255)),
                ('cardNumber', models.IntegerField(max_length=12)),
                ('expirationDate', models.IntegerField(max_length=4)),
                ('cvc', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='country',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
