# Generated by Django 4.2.1 on 2023-05-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_countries_paymentinfo_contactinfo_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='cardNumber',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='cvc',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='expirationDate',
            field=models.CharField(max_length=255),
        ),
    ]
