# Generated by Django 4.2.1 on 2023-05-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='description',
            field=models.CharField(default=1, max_length=9999),
            preserve_default=False,
        ),
    ]
